### PR TITLE
fix: Use custom plural of Repository model

### PR DESCRIPTION
**Pull request by bibliotechy**
"Repositorys" makes my eyes want to bleed. 

🩸 👀 🩸

### CODE REVIEW

**Comment by bibliotechy** [comment]
OK, this also needs me to add the migrations, but I can't do that locally without having a local DB, which I'm not entirely clear how to do. Maybe a quick session with @everreau next week to get me set up so I can contribute to this and then I can update the docs to reflect what we have done.

**Comment by amywieliczka** [comment]
`docker compose -f cincoctrl/docker-compose.local.yml up` should get you a local postgres db - the local environment variables are even checked into the repo (and used during the ci process). I don't think anything else is required. 

but also...the reorg PR I'm about to merge moves this file.

**Comment by amywieliczka** [comment]
Ohhh, you'll also need to run `docker compose -f cincoctrl/docker-compose.local.yml python manage.py migrate` I think?

**Comment by bibliotechy** [comment]
@amywieliczka OK, I ran `docker compose -f docker-compose.local.yml run django python manage.py migrate` which is quite the mouthful :)

**Pull request merged**
